apiVersion: v1
kind: Service
metadata:
  name: cache-server
spec:
  ports:
  - name: 40404-40404
    port: 40404
    protocol: TCP
    targetPort: 40404
  selector:
    app: cache-server
  type: ClusterIP